# Generated by Django 2.0.2 on 2018-03-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_subtask_subtaskskill_userskill_usersubtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubtask',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='usersubtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSubtask',
        ),
    ]
